# == Class: zabbix::server::params
#
# This class manages Zabbix server parameters
#
# === Authors
#
# Eric Anderson <eric.sysmin@gmail.com>
#
class zabbix::server::params (
  $dbType                  = 'mysql',
  $nodeID                  = undef,
  $listenPort              = undef,
  $sourceIP                = undef,
  $logFile                 = '/var/log/zabbix/zabbix_server.log',
  $logFileSize             = '0',
  $debugLevel              = undef,
  $pidFile                 = '/var/run/zabbix/zabbix_server.pid',
  $dbHost                  = undef,
  $dbName                  = 'zabbix',
  $dbSchema                = undef,
  $dbUser                  = undef,
  $dbPassword              = undef,
  $dbSocket                = undef,
  $dbPort                  = undef,
  $startPollers            = undef,
  $startIPMIPollers        = undef,
  $startPollersUnreachable = undef,
  $startTrappers           = undef,
  $startPingers            = undef,
  $startDiscoverers        = undef,
  $startHTTPPollers        = undef,
  $startTimers             = undef,
  $javaGateway             = undef,
  $javaGatewayPort         = undef,
  $startJavaPollers        = undef,
  $startVMwareCollectors   = undef,
  $vmwareFrequency         = undef,
  $vmwareCacheSize         = undef,
  $snmpTrapperFile         = undef,
  $startSNMPTrapper        = undef,
  $listenIP                = undef,
  $housekeepingFrequency   = undef,
  $maxHousekeeperDelete    = undef,
  $senderFrequency         = undef,
  $cacheSize               = undef,
  $cacheUpdateFrequency    = undef,
  $startDBSyncers          = undef,
  $historyCacheSize        = undef,
  $trendCacheSize          = undef,
  $historyTextCacheSize    = undef,
  $valueCacheSize          = undef,
  $nodeNoEvents            = undef,
  $nodeNoHistory           = undef,
  $timeout                 = undef,
  $trapperTimeout          = undef,
  $unreachablePeriod       = undef,
  $unavailableDelay        = undef,
  $unreachableDelay        = undef,
  $alertScriptsPath        = '/usr/lib/zabbix/alertscripts',
  $externalScripts         = '/usr/lib/zabbix/externalscripts',
  $fpingLocation           = '/usr/bin/fping',
  $fping6Location          = '/usr/bin/fping6',
  $sshKeyLocation          = undef,
  $logSlowQueries          = undef,
  $tmpDir                  = undef,
  $startProxyPollers       = undef,
  $proxyConfigFrequency    = undef,
  $proxyDataFrequency      = undef,
  $allowRoot               = undef,
  $include                 = undef,
  $loadModulePath          = undef,
  $loadModule              = undef,) {
}
